[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "ISC",
    "Unicode-3.0",
]
confidence-threshold = 0.8
# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    { allow = [
        "OpenSSL",
    ], name = "ring" },
    { allow = [
        "BSD-3-Clause",
    ], crate = "matchit" },
    { allow = [
        "BSD-3-Clause",
    ], crate = "subtle" },
    { allow = [
        "MPL-2.0",
    ], crate = "webpki-roots" },
    { allow = [
        "CC0-1.0",
    ], crate = "tiny-keccak" },
    { allow = [
        "BSL-1.0",
    ], crate = "error-code" },
    { allow = [
        "BSL-1.0",
    ], crate = "clipboard-win" },
    { allow = [
        "BSD-2-Clause",
    ], crate = "Inflector" },
]
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
