[licenses]
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "Zlib", "ISC"]
confidence-threshold = 0.8
# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    { allow = [
        "ISC",
        "OpenSSL",
    ], crate = "aws-lc-rs" },
    { allow = [
        "OpenSSL",
    ], name = "ring" },
    { allow = [
        "ISC",
        "OpenSSL",
    ], crate = "aws-lc-sys" },
    { allow = [
        "BSD-3-Clause",
    ], crate = "bindgen" },
    { allow = [
        "BSD-3-Clause",
    ], crate = "matchit" },
    { allow = [
        "BSD-3-Clause",
    ], crate = "subtle" },
    { allow = [
        "MPL-2.0",
    ], crate = "webpki-roots" },
    { allow = [
        "Unicode-3.0",
    ], crate = "unicode-ident" },
]
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
