[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["tracing", "macros", "headers"] }
const_format = { version = "0.2.31", features = ["fmt"] }
serde = { workspace = true }
tokio = { version = "1.32.0", features = ["full", "tracing"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json", "local-time"] }
