[package]
name = "mergeable-compatibility-layer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
tracing = { workspace = true }
