[package]
name = "mergeable-compatibility-layer"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_yaml = "0.9.34"
