[package]
name = "mergeable-compatibility-layer"
version.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
