name: Check
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  check-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use cachix binary cache
        uses: cachix/cachix-action@v12
        with:
          name: source-fox
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Build project
        run: nix build
      - name: Run checks
        run: nix flake check